language: python
python:
  - "2.7"
  - "3.4"
before_install:
  - Xvfb :12 -screen 0 800x600x24 +extension RANDR &
env:
  secure: JuKMjiXidl1lP5bwLnvd9Mh4d+NSr9icKgrP0qhfGjQxt5CRqc5ZXqB860bh5YXhAlPGvJJDfKJF5ZvKqLzKJ5f7R/83+wM75nQOW9ytM4EsnPghb42+JLw0MQrOVx7Rf+XGv57sgFqNuFM0e8Fieew+hKKHTv2kzs0Pgh+nV7IocN2o1Fx8iWccDeYvgy+YHG4CxqdQzVvd4A0h/WPVG0TehIzhRjNDZkf3iliUfAlUKf/QI6OVv2gCQsGl28K/jEk8XHHrWAC+F23eFUSiXbvYbbkNVLwqj11Qw64vTLIyKFYD3a9UxK2agldk2eAoeXjGp1vCY8hy7vWRaUuc7ilHkO2dvJO9b3oCLgtzmGvIyJc5USI3CEQ50uazK0q3qQ2ZVs/JZt/QQ+UdMLkdHewWXeSs8IWOcMMWCaIINriOJmnxDzeMDghb1yoQWeRiCrD2feDwZ8fiAvkZ9Gfql8Wbu1Yb49lGSJAvRb5+Ysegh8xactprtXUdoGJxakwHvKlfIUNG2b8M6h+LvFJMYuH32G6ZjFI/HulDbCTGAd+kyfyJuP5MOm/q9uODZLQPuowMpm+qPjOhSXBni+xdPAtrN+LSOUG2BniK3gW4MCayGgGbRl7V0nxW6EcZQpy7cqIZEQpa6ZLNEjSgzUDxg0pO9yEVpfdSj4SrLjq+A6A=
  # contains encrypted API key to upload
install: "pip install -r requirements.txt"
script: nose2